### ISSUE TITLE
Error when using oaip

### ISSUE THREAD

**Issue by verdesroches** [lboekhorst/oaip#1]
I'm trying to use oaip on my computer with ruby 1.9.3. When I run oaip (I get the same error when I run oaip with or without file as argument, or with the --help parameter), I get error : 
/var/lib/gems/1.9.1/gems/oaip-0.7.0/lib/oaip/parser.rb:52:in `parser': uninitialized constant OAIP::Parser::OptionParser (NameError)
        from /var/lib/gems/1.9.1/gems/oaip-0.7.0/lib/oaip/parser.rb:6:in `parse'
        from /var/lib/gems/1.9.1/gems/oaip-0.7.0/exe/oaip:5:in `<top (required)>'
        from /usr/local/bin/oaip:23:in `load'
        from /usr/local/bin/oaip:23:in `<main>'

Any idea about that ?

Thank you

**Comment by lboekhorst** [comment]
Hi verdesroches, thanks for reporting this. I have just pushed a new version to RubyGems so would you be able to run a `gem update oaip` and try again? Although I do not seem to be able to reproduce this locally, it most likely has to do with the fact that `optparse` was not properly required.

**Comment by verdesroches** [comment]
Thank you, problem fixed !
